### ISSUE TITLE
Exception with Duration analysis

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#20]
Occurs after Phones query followed by Stock Duration Analysis report. I include all the materials (session, query, WAV file and associated TextGrid) through the following link:

https://www.dropbox.com/s/md2hjtnk7bmhg7x/Duration.zip?dl=0

The error message (below) occurs when I run this query on Phon 3.0.0 for Windows. The puzzling thing is that I have no issue running the exact same routine on macOS. 

Duration/Duration (14bfa1b485cf427c)
ca.phon.opgraph.exceptions.ProcessingException: An error occured during the processing of a graph
	at ca.phon.opgraph.Processor.processCurrentNode(Processor.java:345)
	at ca.phon.opgraph.Processor.step(Processor.java:292)
	at ca.phon.opgraph.Processor.stepAll(Processor.java:478)
	at ca.phon.opgraph.Processor.stepAll(Processor.java:491)
	at ca.phon.opgraph.nodes.general.MacroNode.operate(MacroNode.java:218)
	at ca.phon.opgraph.Processor.processCurrentNode(Processor.java:330)
	at ca.phon.opgraph.Processor.step(Processor.java:292)
	at ca.phon.opgraph.Processor.stepAll(Processor.java:478)
	at ca.phon.opgraph.Processor.stepAll(Processor.java:491)
	at ca.phon.app.opgraph.wizard.NodeWizard.executeGraph(NodeWizard.java:826)
	at ca.phon.app.opgraph.wizard.NodeWizard.lambda$gotoStep$21(NodeWizard.java:1199)
	at ca.phon.worker.PhonWorker.run(PhonWorker.java:141)
Caused by: java.lang.NullPointerException
	at ca.phon.plugins.praat.opgraph.PraatNode.operate(PraatNode.java:179)
	at ca.phon.opgraph.Processor.processCurrentNode(Processor.java:330)
	... 11 more

**Comment by yrose** [comment]
The TextGrid was generated using Phon and manually aligned based on the methods we designed in Phon. There must be a reason for that null pointer to occur.

**Comment by yrose** [comment]
This ZIP only contains the TextGrid file

[010605.TextGrid.zip](https://github.com/phon-ca/phon/files/2410854/010605.TextGrid.zip)

**Comment by ghedlund** [comment]
Ok, so finally on this:

 1) The TextGrid you sent was fine - vim was not using the correct unicode format (I had it forced to UTF-8 and TextGrids are UTF-16)
 2) The Duration report worked without issue
 3) The TextGrid does indeed have data (once I looked far enough in the session)

So, everything appears to be working correctly on my end with the TextGrid file you sent today.

-Greg
